CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS rockets (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name VARCHAR(50),
  type VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);